version: "3.1"
services:
  proxy:
    build: 
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - load-balancer-network  
    
  microservice-devops-1:
    image: erickespinozat/nodejs-api:test-6bbe668
    container_name: microservice-devops-1
    # hostname: microservice-devops-1
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - load-balancer-network
      
  microservice-devops-2:
    image: erickespinozat/nodejs-api:test-6bbe668
    # hostname: microservice-devops-2
    container_name: microservice-devops-2
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - load-balancer-network
networks:
  load-balancer-network:
    name: load-balancer-network
