version: "3.5"

services:
  nodejs-server:
    image: erickespinozat/nodejs-api:latest
    container_name: nodejs-api
    restart: unless-stopped
    ports:
      - "3000:3000"
networks:
  - app-network