version: "3.5"

services:
  nodejs-server:
    networks:
      - webgateway-nodejs
    image: erickespinozat/nodejs-api:latest
    container_name: nodejs-api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodejs.rule=Host(`nodejs.unknwnrrr.dev`)"
      - "traefik.http.routers.nodejs.entrypoints=websecure"
      - "traefik.http.services.nodejs.loadbalancer.server.port=3000"
      - "traefik.http.routers.nodejs.service=nodejs"
      - "traefik.http.routers.nodejs.tls.certresolver=leresolver"
networks:
  webgateway-nodejs:
    external:
     name: webgateway_network