name: Build
on:
  push:
    branches: [master, test, cicd] # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar:
    name: Sonarqube Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  build-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
# on:
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Person to greet'
#         required: true
#         default: 'Mona the Octocat'
#       home:
#         description: 'location'
#         required: false
#         default: 'The Octoverse'

# jobs:
#   say_hello:
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "Hello ${{ github.event.inputs.name }}!"
#           echo "- in ${{ github.event.inputs.home }}!"
