name: 'Building Production Package'
on:
  push:
    branches: [test] # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  tag-release:
    name: Generate Tag Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  docker-image:
      name: Building Docker Image Production
      needs: [tag-release]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build and Push Docker Image of branche
          uses: mr-smithers-excellent/docker-build-push@v5
          with:
            image: erickespinozat/nodejs-api
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tag: ${{ jobs.tag-release.outputs.tag }}
