name: 'tag'
on:
  push:
    branches: [master, test, cicd] # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # version_regex: 'Version: ([0-9]+\.[0-9]+\.[0-9]+)'
        version_tag_prefix: 'v'
  docker-image:
      name: Building Docker Image
      needs: [tag]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Build and Push Docker Image of branche
          uses: mr-smithers-excellent/docker-build-push@v5
          with:
            image: erickespinozat/nodejs-api
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            addLatest: true
